#!/usr/bin/env python3
"""Rehearsal migrator: Hodler Suite web_portal SQLite databases -> PostgreSQL.

Read-only on SQLite: never modifies or deletes the source .db files.

Unlike a hand-maintained per-app migrator, this dynamically introspects each
SQLite database's schema (web_portal's 8 stores are numerous and evolve
independently - hand-tracking every table would go stale fast) and creates
an equivalent Postgres schema, then copies data in batches.

Each SQLite file becomes its own Postgres SCHEMA (support_tickets, billing,
web_portal_auth, ...) inside one rehearsal database, preserving the existing
one-file-per-concern separation rather than flattening everything together.

Usage:

    # Dry-run (counts + schema plan only, no writes)
    python3 migrate_web_portal_to_postgres.py \
      --data-dir /opt/hodler-suite/web_portal/data \
      --database-url postgresql://hodler_rehearsal:PASSWORD@127.0.0.1:5432/hodler_suite_rehearsal \
      --dry-run

    # Full migrate (resumable)
    python3 migrate_web_portal_to_postgres.py \
      --data-dir /opt/hodler-suite/web_portal/data \
      --database-url postgresql://hodler_rehearsal:PASSWORD@127.0.0.1:5432/hodler_suite_rehearsal \
      --resume
"""

from __future__ import annotations

import argparse
import json
import logging
import re
import sqlite3
import sys
import time
from pathlib import Path
from typing import Any

LOGGER = logging.getLogger("migrate_web_portal_to_postgres")

DEFAULT_BATCH = 5_000
STATE_NAME = "migrate_web_portal_to_postgres.state.json"
REPORT_NAME = "migrate_web_portal_to_postgres.report.json"

# One SQLite file -> one Postgres schema. Filenames match /opt/hodler-suite/web_portal/data/*.db.
DB_FILES = [
    "support_tickets",
    "web_portal_auth",
    "billing",
    "risk_jobs",
    "status_metrics",
    "token_lists",
    "marketing_outreach",
    "usage_statistics",
]

_IDENT_RE = re.compile(r"^[A-Za-z_][A-Za-z0-9_]*$")


def _configure_logging(verbose: bool) -> None:
    logging.basicConfig(
        level=logging.DEBUG if verbose else logging.INFO,
        format="%(asctime)s %(levelname)s %(message)s",
    )


def _safe_ident(name: str) -> str:
    """Reject anything that isn't a plain identifier before it goes anywhere near SQL."""
    if not _IDENT_RE.match(name):
        raise ValueError(f"unsafe identifier: {name!r}")
    return name


def _load_state(path: Path) -> dict[str, Any]:
    if not path.exists():
        return {"completed": [], "tables": {}}
    try:
        return json.loads(path.read_text(encoding="utf-8"))
    except json.JSONDecodeError:
        return {"completed": [], "tables": {}}


def _save_state(path: Path, state: dict[str, Any]) -> None:
    path.write_text(json.dumps(state, indent=2, sort_keys=True), encoding="utf-8")


def _sqlite_table_names(conn: sqlite3.Connection) -> list[str]:
    rows = conn.execute(
        "SELECT name FROM sqlite_master WHERE type='table' "
        "AND name NOT LIKE 'sqlite_%' ORDER BY name"
    ).fetchall()
    return [str(r[0]) for r in rows]


def _sqlite_columns(conn: sqlite3.Connection, table: str) -> list[dict[str, Any]]:
    rows = conn.execute(f"PRAGMA table_info({_safe_ident(table)})").fetchall()
    # cid, name, type, notnull, dflt_value, pk
    return [
        {
            "name": r[1],
            "type": (r[2] or "").upper(),
            "notnull": bool(r[3]),
            "default": r[4],
            "pk": bool(r[5]),
        }
        for r in rows
    ]


def _sqlite_unique_indexes(conn: sqlite3.Connection, table: str) -> list[list[str]]:
    """Return column-name groups covered by a UNIQUE index (excluding the PK itself)."""
    out: list[list[str]] = []
    for idx in conn.execute(f"PRAGMA index_list({_safe_ident(table)})").fetchall():
        idx_name, unique, origin = idx[1], bool(idx[2]), idx[3]
        if not unique:
            continue
        cols = [
            row[2]
            for row in conn.execute(f"PRAGMA index_info({_safe_ident(idx_name)})").fetchall()
        ]
        if cols:
            out.append(cols)
    return out


def _translate_type(sqlite_type: str, *, is_single_pk: bool) -> str:
    t = sqlite_type.upper()
    if is_single_pk and ("INT" in t):
        return "BIGINT GENERATED BY DEFAULT AS IDENTITY"
    if "INT" in t:
        return "BIGINT"
    if any(x in t for x in ("CHAR", "CLOB", "TEXT")):
        return "TEXT"
    if any(x in t for x in ("REAL", "FLOA", "DOUB")):
        return "DOUBLE PRECISION"
    if "NUMERIC" in t or "DECIMAL" in t:
        return "NUMERIC"
    if "BOOL" in t:
        return "BOOLEAN"
    if "BLOB" in t or not t:
        return "BYTEA"
    return "TEXT"  # unknown affinity - safe fallback, never fail the migration on a weird type


def _translate_default(raw_default: Any, pg_type: str) -> str | None:
    """Only translate simple literal defaults. Anything else is dropped -
    migrated rows carry their real values regardless; DEFAULT only matters
    for future inserts, so being conservative here is safe."""
    if raw_default is None:
        return None
    text = str(raw_default).strip()
    if text.upper() in ("CURRENT_TIMESTAMP", "CURRENT_TIME", "CURRENT_DATE"):
        return None  # semantics differ enough between engines - skip, not worth the risk
    if re.match(r"^-?\d+(\.\d+)?$", text):
        return text
    if len(text) >= 2 and text[0] == "'" and text[-1] == "'":
        return text
    return None


def _build_create_schema_sql(schema: str) -> str:
    return f'CREATE SCHEMA IF NOT EXISTS "{_safe_ident(schema)}"'


def _build_create_table_sql(schema: str, table: str, columns: list[dict[str, Any]], unique_groups: list[list[str]]) -> str:
    _safe_ident(schema)
    _safe_ident(table)
    pk_cols = [c["name"] for c in columns if c["pk"]]
    is_single_pk = len(pk_cols) == 1
    col_defs: list[str] = []
    for col in columns:
        _safe_ident(col["name"])
        pg_type = _translate_type(col["type"], is_single_pk=is_single_pk and col["pk"])
        parts = [f'"{col["name"]}"', pg_type]
        if col["notnull"] and not (is_single_pk and col["pk"]):
            parts.append("NOT NULL")
        default_sql = _translate_default(col["default"], pg_type)
        if default_sql is not None:
            parts.append(f"DEFAULT {default_sql}")
        col_defs.append(" ".join(parts))

    if is_single_pk:
        col_defs.append(f'PRIMARY KEY ("{pk_cols[0]}")')
    elif pk_cols:
        quoted = ", ".join(f'"{c}"' for c in pk_cols)
        col_defs.append(f"PRIMARY KEY ({quoted})")

    for group in unique_groups:
        if len(group) == 1 and group == pk_cols:
            continue  # already covered by the PK
        quoted = ", ".join(f'"{c}"' for c in group)
        col_defs.append(f"UNIQUE ({quoted})")

    body = ",\n    ".join(col_defs)
    return f'CREATE TABLE IF NOT EXISTS "{schema}"."{table}" (\n    {body}\n)'


def _count_sqlite(conn: sqlite3.Connection, table: str) -> int:
    row = conn.execute(f'SELECT COUNT(*) FROM "{_safe_ident(table)}"').fetchone()
    return int(row[0] or 0)


def _count_pg(pg_conn: Any, schema: str, table: str) -> int:
    with pg_conn.cursor() as cur:
        cur.execute(f'SELECT COUNT(*) FROM "{schema}"."{table}"')
        return int(cur.fetchone()[0] or 0)


def _copy_table(
    sqlite_conn: sqlite3.Connection,
    pg_conn: Any,
    schema: str,
    table: str,
    columns: list[dict[str, Any]],
    *,
    batch_size: int,
    dry_run: bool,
) -> dict[str, Any]:
    col_names = [c["name"] for c in columns]
    pk_cols = [c["name"] for c in columns if c["pk"]]
    src_count = _count_sqlite(sqlite_conn, table)
    result: dict[str, Any] = {"sqlite_rows": src_count, "copied": 0}

    if dry_run:
        LOGGER.info("[dry-run] %s.%s: %s rows", schema, table, src_count)
        return result
    if src_count == 0:
        result["postgres_rows"] = _count_pg(pg_conn, schema, table)
        LOGGER.info("%s.%s: empty - skip", schema, table)
        return result

    col_list = ", ".join(f'"{c}"' for c in col_names)
    placeholders = ", ".join(["%s"] * len(col_names))
    conflict = f'ON CONFLICT ("{pk_cols[0]}") DO NOTHING' if len(pk_cols) == 1 else "ON CONFLICT DO NOTHING"
    insert_sql = f'INSERT INTO "{schema}"."{table}" ({col_list}) VALUES ({placeholders}) {conflict}'

    sqlite_conn.row_factory = sqlite3.Row
    sqlite_select_cols = ", ".join(f'"{c}"' for c in col_names)
    sqlite_select_sql = f'SELECT {sqlite_select_cols} FROM "{table}" LIMIT ? OFFSET ?'
    offset = 0
    copied = 0
    while offset < src_count:
        rows = sqlite_conn.execute(
            sqlite_select_sql,
            (batch_size, offset),
        ).fetchall()
        if not rows:
            break
        payload = [tuple(row) for row in rows]
        with pg_conn.cursor() as cur:
            try:
                cur.executemany(insert_sql, payload)
                pg_conn.commit()
            except Exception:
                pg_conn.rollback()
                raise
        copied += len(payload)
        offset += len(payload)
        LOGGER.info("%s.%s: copied %s / %s", schema, table, copied, src_count)

    if len(pk_cols) == 1 and pk_cols[0] in col_names:
        with pg_conn.cursor() as cur:
            cur.execute(
                f'SELECT setval(pg_get_serial_sequence(%s, %s), '
                f'COALESCE((SELECT MAX("{pk_cols[0]}") FROM "{schema}"."{table}"), 1), true)',
                (f"{schema}.{table}", pk_cols[0]),
            )
        pg_conn.commit()

    pg_count = _count_pg(pg_conn, schema, table)
    result.update({"copied": copied, "postgres_rows": pg_count})
    if pg_count != src_count:
        LOGGER.warning(
            "%s.%s row-count mismatch: sqlite=%s postgres=%s (ON CONFLICT may have skipped duplicates on resume)",
            schema, table, src_count, pg_count,
        )
    else:
        LOGGER.info("%s.%s: verified %s rows", schema, table, pg_count)
    return result


def migrate(
    *,
    data_dir: Path,
    state_dir: Path,
    database_url: str,
    dry_run: bool,
    resume: bool,
    only: str | None,
    batch_size: int,
) -> int:
    import psycopg

    state_file = state_dir / STATE_NAME
    state_file.parent.mkdir(parents=True, exist_ok=True)
    state = _load_state(state_file) if resume else {"completed": [], "tables": {}}
    completed = set(state.get("completed") or [])

    pg_conn = None if dry_run else psycopg.connect(database_url)
    started = time.time()

    try:
        for db_name in DB_FILES:
            db_path = data_dir / f"{db_name}.db"
            if not db_path.exists():
                LOGGER.warning("skipping %s: file not found at %s", db_name, db_path)
                continue
            if only and only.split(".")[0] != db_name:
                continue

            schema = db_name
            LOGGER.info("=== %s (%s) ===", schema, db_path)
            sqlite_conn = sqlite3.connect(f"file:{db_path}?mode=ro", uri=True)
            try:
                if not dry_run:
                    with pg_conn.cursor() as cur:
                        cur.execute(_build_create_schema_sql(schema))
                    pg_conn.commit()

                tables = _sqlite_table_names(sqlite_conn)
                if only and "." in only:
                    wanted = only.split(".", 1)[1]
                    tables = [t for t in tables if t == wanted]

                for table in tables:
                    key = f"{schema}.{table}"
                    if resume and key in completed:
                        LOGGER.info("%s: already completed - skip (--resume)", key)
                        continue

                    columns = _sqlite_columns(sqlite_conn, table)
                    unique_groups = _sqlite_unique_indexes(sqlite_conn, table)

                    if not dry_run:
                        create_sql = _build_create_table_sql(schema, table, columns, unique_groups)
                        with pg_conn.cursor() as cur:
                            cur.execute(create_sql)
                        pg_conn.commit()

                    info = _copy_table(
                        sqlite_conn, pg_conn, schema, table, columns,
                        batch_size=batch_size, dry_run=dry_run,
                    )
                    state.setdefault("tables", {})[key] = info
                    if not dry_run:
                        completed.add(key)
                        state["completed"] = sorted(completed)
                        _save_state(state_file, state)
            finally:
                sqlite_conn.close()

        if not dry_run and pg_conn is not None:
            with pg_conn.cursor() as cur:
                cur.execute("ANALYZE")
            pg_conn.commit()
    finally:
        if pg_conn is not None:
            pg_conn.close()

    LOGGER.info("Migration finished in %.1fs (dry_run=%s)", time.time() - started, dry_run)
    report_path = state_dir / REPORT_NAME
    report_path.write_text(json.dumps(state, indent=2, sort_keys=True), encoding="utf-8")
    LOGGER.info("Wrote report %s", report_path)
    return 0


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--data-dir", type=Path, required=True, help="Directory containing the 8 web_portal .db files")
    parser.add_argument("--state-dir", type=Path, required=True, help="Directory to write state/report JSON (kept separate from --data-dir)")
    parser.add_argument("--database-url", required=True, help="PostgreSQL connection URL (rehearsal database)")
    parser.add_argument("--dry-run", action="store_true", help="Count rows + log schema plan only; no writes")
    parser.add_argument("--resume", action="store_true", help="Skip schema.table pairs listed in the state file")
    parser.add_argument("--only", default=None, help="Limit to one db (e.g. 'billing') or one table ('billing.billing_webhook_events')")
    parser.add_argument("--batch-size", type=int, default=DEFAULT_BATCH)
    parser.add_argument("-v", "--verbose", action="store_true")
    args = parser.parse_args(argv)
    _configure_logging(args.verbose)
    return migrate(
        data_dir=args.data_dir,
        state_dir=args.state_dir,
        database_url=args.database_url,
        dry_run=args.dry_run,
        resume=args.resume,
        only=args.only,
        batch_size=args.batch_size,
    )


if __name__ == "__main__":
    raise SystemExit(main())
